# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DiADeMTM
email: info@code4health.org
description: > # this means to ignore newlines until "baseurl:"
  DiADeM has been developed by the Yorkshire & Humber Dementia Clinical Network with input from a range of stakeholders including experts in the field of Dementia from across the health spectrum
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://appertafoundation.github.io/diademwebsite" # the base hostname & protocol for your site
twitter_username: diadem_app
github_username:  Apperta

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']